public without sharing class Optiva_NPDCreationWrapper {
    public String project_sf_code='';	//1212123
	public String project_title='';	//ABC XYZ
	public String created_by='';	//Ajeet
	public String creation_date='';	//27/03/2022
	public String project_type='';	//External ..
	public String project_category='';	//Seasoning
	public String opp_type_int='';	//Development
	public String opp_sub_type_sales='';	//NPD
	public String cust_code='';	//TUUYWNMSMMSS
	public String end_use_cat='';	//end-use_category
	public String end_use_appli='';	//end-use_app
	public String cust_target_price='';	//500000
	public String curr_type='';	//Euro
	public String cust_ciu='';	//Cust CUI Number
	public String annual_vol='';	//50000
	public Double business_potent_val;	//78.9
	public String curr_year_vol;	//890000
	public String opp_closedate='';	//23/05/2022
	public String sample_duedate1='';	//23/05/2022 ..
	public String cust_launch_date='';	//23/05/2022
	public String sensry_prfle_rpt='';	//Sensory Profiling Report ..
	public String appl_smpl_recipe='';	//Example of recipe
	public String physical_form='';	//Physical Form
	public String solublity='';	//YES ..
	public String shelf_life_flvr='';	//Sweet ..
	public String supplier_legal_stat='';	//Certified by fssai ..
	public String dosage_guide_cust='';	//Dosage Guide Temp
	public String shelf_life_appl_prod='';	//Shelf Life Application Production ..
	public String appl_guide='';	//Applicance Guidelines
	public String cust_base_details='';	//AK Group food healthify
	public String match_target_dtls='';	//Match Taget Date
	public String sample_size_trails='';	//Sample Size trails ..
	public String sensry_target_prfl='';	//Sensory Taget Profile ..
	public String inputs_by_cust='';	//Amazing Taste
	public String alrgn_free_declare='';	//YES
	public String gmo_status='';	//YES
	public String halal_cert='';	//YES
	public String kosher_cert='';	//YES
	public String legal_status_eu='';	//Legal Status
	public String legal_status_fssai ='';	//FSSAI LEGAL STATUS
	public String legal_status_us ='';	//US LEGAL STATUS
	public String organic_cert = '';	//Organic Certifications
	public String prod_apr_frmat_cust='';	//Product approval format by customer
    
    
    
    //NEW ADDITIONS 
    public String expected_shelf_life = '0';
    public String legal_status = 'NA';
	
}