public class Optiva_Project_Creation_Wrapper {
    public String project_sf_code;
    public String project_title;
    public String project_type;
    public String project_category;
    public String opp_type_int;
    public String opp_sub_type_sales;
    public String prod_spec;
    public String msds;
    public String country_comp;
    public String allergen;
    public String nutritional;
    public String other;
    public String prod_code_dev;
    public String target_date;
    
    //NEW ADDITIONS
    public String cust_code;
    public String created_by;
    
}