public without sharing class OptivaCreateCustomerWrapper {
    public String sf_id;	//0019D00000
	public String customer_grouping;	//Domestic
	public String partner_role;	//Key
	public String customer_name;	//Akhil K G
	public String street_2;	//NO:80,BOMMASANDRA
	public String street_3;	//ANEKAL TALUK, HOSUR ROAD,
	public String street;	//INDUSTRIAL AREA, CHEMBANOOR
	public String postal_Code;	//683572
	public String city;	//ANGAMALY
	public String country;	//IN
	public String region;	//KA
	public String language;	//EN
	public String telephone_number;	//9249500002
	public String mobile_number;	//9249500002
	public String email;	//moolansgroup@gmail.com
	public String gstin_number;	//32AACCM3259N1ZB
	public String pan_number;	//AACCM3259N
}