public without sharing class SAP_PROJECT_CREATION_WRAPPER {
	public String CUSTOMER_CODE;	//1234ABD --
    public String REF_CODE;	//1234ABD -- 
	public String PROJECT_CODE;	//D/0001148 --
	public String PROJECT_INITIATED_BY;	//JOHN SMITH --
	public String APP_NAME;	//SYMEGA --
	public String PROJECT_CATEGORY;	//FOOD SERVICES -- 
	public String PROJECT_NAME;	//SYMEGA --
	public String APPROVER_NAME;	//ROBERT --
	public String SALES_HEAD_REVIEW;	//MARIEL --
	public String CUSTOMER_CONTACT;	//2039320IWEWIOEWI -- 
	public String COUNTRY_REGULATION;	//FSSAI --
	public Decimal COST_IN_USE;	//100 --
	public String CUSTOMER_COMMENTS; //--
	public String DOSAGE_GUIDELINE;	// -- 
	public String MATCHING_TARGET_DETAILS;	// --
	public String PRODUCT_APP_CUSTOMER;	// 
	public String ADDITIONAL_COMMENTS;	//CREAMY CHEESE,BUTTER FOR KARARE --
	public String APPLICATION_METHOD;	// --
	public String END_APPLICATION_CATEGORY;	//AWESOME --
	public String CUSTOMER_FEEDBACK;	//TASTE AND AFFORDABLE IN COST --
	public String CUSTOMER_LAUNCH_DATE;	// --
	public Decimal EXPECTED_ANNUAL_VALUE;	//200 --
	public String EXPECTED_SHELF_LIFE;	//6 MONTHS --
	public String EXPECTED_VOLUME_UNIT;	//TONNES --
	public String IF_PRIVATE_LABEL;	//100 --
	public String INGREDIENT_SPECIFIC_IF_ANY;	//TOMATTO --
	public Decimal MINIMUM_ORDER_QUANTITY;	//23 --
	//public String MINIMUM_ORDER_QUANTITY_UNIT;	//TONNES
	public String OTHER_APPLICATION_METHODS;	// --
	public String OTHER_PROJECT_COMPOSITION;	//E --
	public String PACKAGING_UNIT;	//KGS --
	public String PROPOSED_DATE_OF_DISPATCH;	// --
	public String PROTOTYPE_FEEDBACK;	// --
	public Decimal QUANTITY;	//10 --
	public String QUANTITY_UNIT;	// --
	public String REGULATORY_REQUIREMENTS;	// --
	public String REQUIRED_END_DATE;	//2023-04-12 --
	public Decimal SAMPLING_QUANTITY_DETAILS;	//34 --
	public String SAMPLING_QUANTITY_UNIT;	//KG --
	public String SOLUBILITY_PREFERENCE;	//GOOD INTO THIS --
	public String SOLUBLITY;	// --
	public String SPECIFIC_INPUTS_BY_CUSTOME;	// --
	public String SUGAR;	// --
	public String SUPPLIER_LEGAL_STATUS;	// --
	public String TARGET_DATE;	// --
	public Decimal TARGET_PRICE;	//2200 --
	public String WET_DRY;	//CPD --
	public String WHERE_USED;	// -- 
	public String STATUS;	//MKAP --
	public String REASON_FOR_REJECTION;	// -- 
	public BOOLEAN ALLERGIN_FREE_DECLERATION;  //--
	public BOOLEAN GMO_STATUS; // --
	public BOOLEAN HALAL_CERTIFICATION; // --
	public BOOLEAN KOSHER_CERTIFICATION; // --
	public String LEGAL_STATUS_AS_PER_US;	//VALID // -- 
	public String LEGAL_STATUS_AS_PER_EU;	//INVALID // --
	public BOOLEAN ORGANIC_CERTIFICATION; // --
	public String ORDER_TYPE; //--
	public String CUSTOMER_PHONE; // --
	public String PRODUCT_FAMILY; // --
	public String TYPE_OF_PR; //--
    
    //NEW
    public Decimal ANNUAL_VOLUME;	//2200 -- 
    public Decimal BUSINESS_POTENTIAL_VALUE;	//2200 --
}